sachindevtomar/FEEHub

src/app/Shared/user.ts, src/app/Shared/users.ts, src/app/header/header.component.html, src/app/header/header.component.scss, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/home.component.ts
Added Welcome Annotation
- User Name 
- User Role
For now, user information is hard coded
=> Added Welcome Annotations

src/app/footer/footer.component.html, src/app/footer/footer.component.scss
Added google map iframe for the MAQ offices locations and also modified the existing footer component.
**UI**:
=> Added MAQ location maps under the footer section

src/app/footer/footer.component.html, src/app/footer/footer.component.scss, src/app/header/header.component.html
* Fixed the accessibility issues and following is the screenshot with no accessibility bug
**UI**:
=> Fixed the accessibility issues in the footer section

src/app/Shared/course.ts, src/app/Shared/courses.ts, src/app/Shared/feature.ts, src/app/Shared/features.ts, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/home.component.ts
Added Course and Feature tiles with Accessibility
=> Added Course and Feature tiles

src/app/courses/courses.component.html, src/app/courses/courses.component.scss, src/app/courses/courses.component.ts
=> Added technologies in a filter view

src/app/components/courses/courses.component.html, src/app/components/courses/courses.component.ts, src/main.ts
=> Added tags filter on the course page

src/app/components/courses/courses.component.html, src/app/components/courses/courses.component.scss, src/app/components/courses/courses.component.ts
**UI of the Course Information section**
**UI of the filters**
** UI of the Error message**
=> Add duration filter and update the UI of the course Page

src/app/components/courses/courses.component.html, src/app/components/courses/courses.component.scss, src/app/components/courses/courses.component.ts, src/app/components/footer/footer.component.html, src/app/components/header/header.component.html
1. Added focus for intractable elements
2. Highlighted intractable elements on hover and focus
3. Fixed Accessibility issues of Courses page and footer
=> Small changes in UI and fix accessibility issues of Courses page

src/app/components/courses/courses.component.html, src/app/components/courses/courses.component.scss, src/app/components/courses/courses.component.ts
**UI for the duration on each course**
* Scroll bar if tags light is more than 400px after clicking view more
* Fluctuation is removed for the courses on hover
* Pagination issue is fixed by taking another variable
=> Fixed pagination Issue and made UI changes on Course Page

src/app/Shared/users.ts, src/app/app-routing/routes.ts, src/app/components/editprofile/editprofile.component.html, src/app/components/editprofile/editprofile.component.scss, src/app/components/editprofile/editprofile.component.spec.ts, src/app/components/editprofile/editprofile.component.ts, src/app/components/editprofile/editprofile.module.ts, src/app/components/editprofile/editprofile.route.ts, src/app/components/header/header.component.html, src/app/models/user.ts
1. Updated Users modal - added claims, email, id and phone numbers
2. Added Edit Profile component
3. Added route for Edit profile
4. Created basic responsive UI of Edit profile
=> Added Edit profile component with module and route file

src/app/_helpers/authenticationLogin.ts, src/app/components/add-claim-modal/add-claim-modal.component.html, src/app/components/add-claim-modal/add-claim-modal.component.spec.ts, src/app/components/add-claim-modal/add-claim-modal.component.ts, src/app/components/editprofile/editprofile.component.html, src/app/components/editprofile/editprofile.component.scss, src/app/components/editprofile/editprofile.component.ts, src/app/components/editprofile/editprofile.module.ts
1. Added modal for adding claims
2. Added user details in edit profile fields
3. Added Save and Cancel buttons
=> Added buttons in edit profile

src/app/Shared/users.ts, src/app/_helpers/authenticationLogin.ts, src/app/_helpers/helper.methods.ts, src/app/components/home/home.component.html, src/app/components/home/home.component.ts, src/app/components/home/home.module.ts
1. User who does has all the claims 
2. User who does not has CanViewCourses claim
3. User who does not have any claims
=> Added claims in the user Object and claim protected home page

src/app/_helpers/helper.methods.ts, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/home/home.component.ts
**When user have course and features both claims**
**When user has only course claim**
**When user has only feature claim**
**When user doesn't have any claims (course or feature) **
=> Added multiple views on home for different claims

src/app/Shared/features.ts, src/app/components/home/home.component.html, src/app/components/home/home.component.scss, src/app/components/login/login.component.html, src/app/components/login/login.component.scss
1. Updated login UI
2. Updated buttons in home page
=> Login and Home UI changes

src/app/components/editprofile/editprofile.component.html, src/app/components/editprofile/editprofile.component.scss
=> Update edit profile page -1

package-lock.json, package.json, src/app/Shared/users.ts, src/app/components/editprofile/editprofile.component.html, src/app/components/editprofile/editprofile.component.scss, src/app/components/editprofile/editprofile.module.ts
=> Added Preference Tag Input on the Edit Profile Page

src/app/app-routing/routes.ts, src/app/app.module.ts, src/app/components/coursedetails/coursedetails.component.html, src/app/components/coursedetails/coursedetails.component.scss, src/app/components/coursedetails/coursedetails.component.spec.ts, src/app/components/coursedetails/coursedetails.component.ts, src/app/components/coursedetails/coursedetails.module.ts, src/app/components/coursedetails/coursedetails.route.ts, src/app/components/courses/courses.component.html, src/app/components/home/home.component.html, src/app/components/home/home.module.ts
=> Added Course Detail page

src/app/components/courses/courses.component.scss, src/app/components/features/features.component.html, src/app/components/features/features.component.scss, src/app/components/header/header.component.scss, src/app/components/home/home.component.html, src/app/components/home/home.component.scss
1. Updated Features page heading, toggle and Feature + button
2. Updated heading Font-size for all the heading in website
3. Added Focus for all intractable elements
4. Changed hover color for header
=> Update styling across the website

src/app/components/courses/courses.component.html, src/app/components/courses/courses.component.scss, src/app/components/courses/courses.component.ts, src/app/components/courses/courses.module.ts, src/styles.scss
=> Made changes in the filter section UI and duration filter

src/app/components/courses/courses.component.html, src/app/components/courses/courses.component.scss, src/app/components/courses/courses.component.ts, src/app/components/courses/courses.module.ts
=> Added Course details in Courses Page

src/app/components/courses/courses.component.spec.ts
=> Fixed test cases for course component

src/app/components/courses/courses.component.spec.ts, src/app/components/courses/courses.component.ts
=> Added Course component test cases

src/app/components/add-claim-modal/add-claim-modal.component.html, src/app/components/add-claim-modal/add-claim-modal.component.scss, src/app/components/add-feature-modal/add-feature-modal.component.html, src/app/components/add-feature-modal/add-feature-modal.component.scss, src/app/components/editprofile/editprofile.component.html, src/app/components/editprofile/editprofile.component.scss, src/app/components/features/features.component.html
**Feature's Modal UI**
**Claim's Modal UI**
** Edit Profile bottom section **
=> Updated Modal UI for the Features and Claims

src/app/components/home/home.component.spec.ts
=> Wrote test for the home component
